const EMPTY_DB = {products:[],stock:[],clients:[],sales:[],audit:[],profiles:[],settings:{storeName:"Tigelinha",currency:"BRL",globalSupport:"",accountTemplate:"Obrigado pela compra! 🥣\n\n🎮 Produto: {produto}\n👤 Nick: {nick}\n🔑 Senha: {senha}{emailLine}\n💬 Suporte: {discord}{observacaoLine}",logoUrl:"tigelinha-logo.webp",keyTemplate:"Obrigado pela compra! 🥣\n\n🎮 Produto: {produto}\n🔑 Key: {key}\n⏳ Plano: {duracao}\n💬 Suporte: {discord}{observacaoLine}"}};
let db=structuredClone(EMPTY_DB), page="dashboard", saleMode="stock", sb=null, session=null, me=null;
const roleNames={owner:"Dono",admin:"Administrador",seller:"Vendedor / Ajudante",support:"Suporte"};
function save(){}
async function log(action,detail,entityType="panel",entityId=null){if(!session)return;await sb.from("audit_log").insert({user_id:session.user.id,action,entity_type:entityType,entity_id:entityId,details:{detail}});await loadAudit();}
async function loadAudit(){const {data}=await sb.from("audit_log").select("*").order("created_at",{ascending:false}).limit(300);db.audit=(data||[]).map(a=>({id:a.id,date:a.created_at,action:a.action,detail:a.details?.detail||"",user:db.profiles.find(p=>p.id===a.user_id)?.displayName||"Usuário"}));}
async function loadData(){
 const [pr,pl,st,cl,sa,se,au,pf]=await Promise.all([
  sb.from("products").select("*").order("created_at"), sb.from("product_plans").select("*").order("created_at"), sb.from("stock").select("*").order("created_at",{ascending:false}), sb.from("clients").select("*").order("created_at",{ascending:false}), sb.from("sales").select("*").order("created_at",{ascending:false}), sb.from("settings").select("*").eq("id",1).maybeSingle(), sb.from("audit_log").select("*").order("created_at",{ascending:false}).limit(300), sb.from("profiles").select("*").order("created_at")
 ]);
 const errs=[pr,pl,st,cl,sa,se,au,pf].map(x=>x.error).filter(Boolean); if(errs.length) throw errs[0];
 db.profiles=(pf.data||[]).map(x=>({id:x.id,username:x.username,displayName:x.display_name,role:x.role,active:x.active,created:x.created_at}));
 const plans=pl.data||[];
 db.products=(pr.data||[]).map(x=>({id:x.id,type:x.type,name:x.name,description:x.description||"",price:0,low:x.low_stock,active:x.active,variants:plans.filter(v=>v.product_id===x.id).map(v=>({id:v.id,label:v.name,price:Number(v.price),discord:v.discord_url||"",template:v.delivery_template||"",durationType:v.duration_type}))}));
 db.stock=(st.data||[]).map(x=>({id:x.id,productId:x.product_id,variantId:x.plan_id,type:x.type,key:x.key_value,username:x.username,password:x.password,email:x.email,price:Number(x.price||0),observation:x.observation||"",status:x.status,created:x.created_at,validity:plans.find(v=>v.id===x.plan_id)?.name||""}));
 db.clients=(cl.data||[]).map(x=>({id:x.id,name:x.name,discord:x.discord||"",notes:x.notes||"",created:x.created_at}));
 db.sales=(sa.data||[]).map(x=>({uuid:x.id,id:x.sale_code,date:x.created_at,productId:x.product_id,variantId:x.plan_id,stockId:x.stock_id,clientId:x.client_id,price:Number(x.price),payment:x.payment_method||"",status:x.status,note:x.note||"",delivery:x.delivery_message||"",createdBy:x.created_by}));
 const s=se.data||{}; db.settings={storeName:s.store_name||"Tigelinha",currency:s.currency||"BRL",globalSupport:s.global_support||"",logoUrl:s.logo_url||"tigelinha-logo.webp",accountTemplate:s.default_account_template||EMPTY_DB.settings.accountTemplate,keyTemplate:s.default_key_template||EMPTY_DB.settings.keyTemplate};
 db.audit=(au.data||[]).map(a=>({id:a.id,date:a.created_at,action:a.action,detail:a.details?.detail||"",user:db.profiles.find(p=>p.id===a.user_id)?.displayName||"Usuário"}));
}
function showLogin(message="") {
  const logo=db.settings?.logoUrl||"tigelinha-logo.webp";
  document.body.innerHTML=`<div class="login-shell"><form class="login-card" id="loginForm"><img class="login-brand-image" src="${esc(logo)}" alt="Tigelinha"><h1>TIGELINHA</h1><p>Acesso ao Control Center</p><div class="field"><label>E-mail</label><input class="input" id="loginEmail" type="email" autocomplete="username" required></div><div class="field" style="margin-top:12px"><label>Senha</label><input class="input" id="loginPassword" type="password" autocomplete="current-password" required></div><button class="btn primary" type="submit">Entrar</button><div class="login-error" id="loginError">${esc(message)}</div></form></div>`;
  document.getElementById("loginForm").addEventListener("submit",async e=>{
    e.preventDefault(); const b=e.submitter; b.disabled=true; b.textContent="Entrando...";
    const {data,error}=await sb.auth.signInWithPassword({email:document.getElementById("loginEmail").value.trim(),password:document.getElementById("loginPassword").value});
    if(error||!data?.session){document.getElementById("loginError").textContent="E-mail ou senha inválidos.";b.disabled=false;b.textContent="Entrar";return;}
    location.reload();
  });
}
async function boot(){const cfg=window.TIGELINHA_SUPABASE;if(!cfg?.url||!cfg?.key)return showLogin("Supabase não configurado.");sb=window.supabase.createClient(cfg.url,cfg.key);const {data}=await sb.auth.getSession();if(!data.session)return showLogin();await startSession(data.session);sb.auth.onAuthStateChange(async(event,s)=>{if(event==="SIGNED_OUT")location.reload();if(event==="SIGNED_IN"&&s&&!session)await startSession(s);});}
async function startSession(s){session=s;const {data:profile,error}=await sb.from("profiles").select("*").eq("id",s.user.id).single();if(error||!profile?.active){await sb.auth.signOut();return showLogin("Usuário sem acesso ou desativado.");}me={id:profile.id,username:profile.username,displayName:profile.display_name||profile.username,role:profile.role,active:profile.active};await loadData();document.querySelector(".app").style.display="flex";applyPermissions();render();}
function applyPermissions(){const n=document.getElementById("userName"),r=document.getElementById("userRole"),a=document.getElementById("userAvatar");if(n)n.textContent=me.displayName||me.username;if(r)r.textContent=roleNames[me.role]||me.role;if(a)a.textContent=(me.displayName||"T").slice(0,1).toUpperCase();document.querySelectorAll('[data-page="team"]').forEach(x=>x.style.display=me.role==="owner"?"flex":"none");document.querySelectorAll('[data-page="audit"]').forEach(x=>x.style.display=["owner","admin"].includes(me.role)?"flex":"none");document.querySelectorAll('[data-page="settings"],[data-page="automation"],[data-page="products"]').forEach(x=>x.style.display=["owner","admin"].includes(me.role)?"flex":"none");document.querySelectorAll(".brand-logo-img").forEach(x=>x.src=db.settings.logoUrl||"tigelinha-logo.webp");}

function money(n) { return new Intl.NumberFormat("pt-BR", {style:"currency", currency:db.settings?.currency || "BRL"}).format(Number(n)||0); }
function esc(s="") { return String(s).replace(/[&<>"']/g, m => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])); }
function fmtDate(d) { return new Date(d).toLocaleDateString("pt-BR"); }
function product(id) { return db.products.find(x => x.id === id) || {}; }
function client(id) { return db.clients.find(x => x.id === id) || {}; }
function stockAvailable(pid, variantId="") { return db.stock.filter(s => s.productId===pid && (!variantId || s.variantId===variantId) && s.status==="available"); }
function variants(p) { return Array.isArray(p.variants) ? p.variants : []; }
function variant(p, id) { return variants(p).find(v => v.id===id) || variants(p)[0] || {}; }
function statusBadge(s) {
  const map={available:["Disponível","green"],reserved:["Reservado","yellow"],sold:["Vendido","blue"],unavailable:["Indisponível","red"],delivered:["Entregue","green"],pending:["Pendente","yellow"],cancelled:["Cancelada","red"]};
  const x=map[s]||[s,s]; return `<span class="badge ${x[1]}">${x[0]}</span>`;
}
function nextSaleId() {
  const nums=db.sales.map(s=>Number(String(s.id).split("-").pop())||0);
  return `TG-${new Date().getFullYear()}-${String(Math.max(0,...nums)+1).padStart(6,"0")}`;
}
function layout(title, sub, buttons="") { return `<div class="page-title"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${buttons}</div></div>`; }
function render(){
  document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));
  const c=document.getElementById("content");
  ({dashboard,sales,stock,clients,products,finance,automation,audit,team,settings}[page]||dashboard)(c);
}

function dashboard(c){
  const delivered=db.sales.filter(s=>s.status==="delivered");
  const revenue=delivered.reduce((a,s)=>a+Number(s.price),0);
  const available=db.stock.filter(s=>s.status==="available");
  const low=db.products.filter(p=>p.active && stockAvailable(p.id).length<=Number(p.low||0));
  const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-6+i);const total=delivered.filter(s=>new Date(s.date).toDateString()===d.toDateString()).reduce((a,s)=>a+Number(s.price),0);return {d,total};});
  const max=Math.max(1,...days.map(x=>x.total));
  c.innerHTML=layout("Dashboard","Visão geral da operação da Tigelinha.",`<button class="btn primary" data-action="newSale">＋ Nova venda</button>`) + `
  <div class="grid cards">
    <div class="card"><div class="stat-top">Faturamento total <div class="stat-icon">💰</div></div><div class="stat-value">${money(revenue)}</div><div class="stat-sub">${delivered.length} vendas entregues</div></div>
    <div class="card"><div class="stat-top">Vendas <div class="stat-icon">🧾</div></div><div class="stat-value">${db.sales.length}</div><div class="stat-sub"><span class="green">${delivered.length} entregues</span> · ${db.sales.filter(s=>s.status==="pending").length} pendentes</div></div>
    <div class="card"><div class="stat-top">Estoque disponível <div class="stat-icon">📦</div></div><div class="stat-value">${available.length}</div><div class="stat-sub">${db.stock.filter(s=>s.type==="account"&&s.status==="available").length} contas · ${db.stock.filter(s=>s.type==="key"&&s.status==="available").length} keys</div></div>
    <div class="card"><div class="stat-top">Estoque baixo <div class="stat-icon">⚠️</div></div><div class="stat-value ${low.length?'yellow':''}">${low.length}</div><div class="stat-sub">${low.length?low.map(p=>esc(p.name)).join(", "):"Tudo dentro do limite"}</div></div>
  </div>
  <div class="grid two">
    <section class="section"><div class="section-head"><b>Vendas dos últimos 7 dias</b><span>${money(days.reduce((a,x)=>a+x.total,0))}</span></div><div class="chart">${days.map(x=>`<div class="bar" style="height:${Math.max(5,x.total/max*165)}px" title="${money(x.total)}"><span>${new Date(x.d).toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","")}</span></div>`).join("")}</div></section>
    <section class="section"><div class="section-head"><b>Produtos com estoque baixo</b><span>${low.length} alertas</span></div>${low.length?`<table><tbody>${low.map(p=>`<tr><td><b>${esc(p.name)}</b><br><small class="muted">${p.type==="account"?"Conta":"Key"}</small></td><td>${stockAvailable(p.id).length}/${p.low}</td><td><button class="btn" data-product="${p.id}" data-action="viewStock">Ver</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">Nenhum alerta de estoque 🎉</div>`}</section>
  </div>
  <section class="section" style="margin-top:14px"><div class="section-head"><b>Últimas vendas</b><button class="btn" data-page="sales">Ver todas</button></div>${salesTable(db.sales.slice(0,6))}</section>`;
}

function salesTable(rows){
  if(!rows.length)return `<div class="empty">Nenhuma venda encontrada.</div>`;
  return `<table><thead><tr><th>ID</th><th>Cliente</th><th>Produto</th><th>Plano</th><th>Valor</th><th>Data</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(s=>{const p=product(s.productId),cl=client(s.clientId),v=variant(p,s.variantId);return `<tr><td><b>${esc(s.id)}</b></td><td>${esc(cl.name||"—")}</td><td>${esc(p.name||"—")}</td><td>${esc(v.label||"—")}</td><td>${money(s.price)}</td><td>${fmtDate(s.date)}</td><td>${statusBadge(s.status)}</td><td><button class="btn" data-sale="${s.id}" data-action="saleDetail">Abrir</button></td></tr>`}).join("")}</tbody></table>`;
}
function sales(c){
  const q=(document.getElementById("globalSearch")?.value||"").toLowerCase();
  const rows=db.sales.filter(s=>{const p=product(s.productId),cl=client(s.clientId),v=variant(p,s.variantId);return !q||[s.id,p.name,v.label,cl.name,cl.discord,s.note].join(" ").toLowerCase().includes(q)});
  c.innerHTML=layout("Vendas","Histórico, entrega e status das vendas.",`<button class="btn primary" data-action="newSale">＋ Nova venda</button>`) + `<div class="filters"><select class="select" style="width:170px" id="saleFilter"><option value="">Todos os status</option><option value="delivered">Entregues</option><option value="pending">Pendentes</option><option value="cancelled">Canceladas</option></select><input class="input" style="max-width:260px" id="saleSearch" placeholder="Filtrar vendas..."></div><section class="section" id="saleTable">${salesTable(rows)}</section>`;
}
function stock(c){
  const accounts=db.products.filter(p=>p.type==="account"&&p.active), keys=db.products.filter(p=>p.type==="key"&&p.active);
  const group=(arr)=>arr.length?arr.map(p=>`<div class="card product-card"><span class="badge">${p.type==="account"?"👤 Conta":"🔑 Key"}</span><h3>${esc(p.name)}</h3><p>${esc(p.description||"")}</p><div class="product-meta"><span><b>${stockAvailable(p.id).length}</b> disponíveis</span><span>${p.type==="key"?variants(p).map(v=>`${esc(v.label)}: ${stockAvailable(p.id,v.id).length}`).join(" · "):money(p.price)}</span><button class="btn" data-product="${p.id}" data-action="viewStock">Gerenciar</button></div></div>`).join(""):`<div class="empty">Nenhum produto nesta categoria.</div>`;
  c.innerHTML=layout("Estoque","Gerencie contas e keys por produto e duração.",`<button class="btn" data-action="newProduct">＋ Adicionar produto</button> <button class="btn primary" data-action="newStock">＋ Adicionar item</button>`) + `<div class="grid product-grid">${group(accounts)}</div><div style="height:18px"></div><div class="section"><div class="section-head"><b>Keys por duração</b><span>${keys.reduce((a,p)=>a+stockAvailable(p.id).length,0)} disponíveis</span></div><div class="grid product-grid" style="padding:14px">${group(keys)}</div></div>`;
}
function clients(c){ c.innerHTML=layout("Clientes","Cadastro e histórico dos seus clientes.",`<button class="btn primary" data-action="newClient">＋ Novo cliente</button>`) + `<section class="section">${db.clients.length?salesClientTable():`<div class="empty">Nenhum cliente cadastrado.</div>`}</section>`; }
function salesClientTable(){return `<table><thead><tr><th>Cliente</th><th>Discord</th><th>Compras</th><th>Total gasto</th><th>Última compra</th><th></th></tr></thead><tbody>${db.clients.map(cl=>{const ss=db.sales.filter(s=>s.clientId===cl.id&&s.status!=="cancelled"),total=ss.reduce((a,s)=>a+Number(s.price),0);return `<tr><td><b>${esc(cl.name)}</b><br><small class="muted">${esc(cl.notes||"")}</small></td><td>${esc(cl.discord||"—")}</td><td>${ss.length}</td><td>${money(total)}</td><td>${ss.length?fmtDate(ss.sort((a,b)=>new Date(b.date)-new Date(a.date))[0].date):"—"}</td><td><button class="btn" data-client="${cl.id}" data-action="clientDetail">Abrir</button></td></tr>`}).join("")}</tbody></table>`; }

function products(c){
  c.innerHTML=layout("Produtos","Cadastre contas ou keys. Keys podem ter Diário, Semanal, Mensal e Lifetime, cada um com preço e Discord próprios.",`<button class="btn primary" data-action="newProduct">＋ Adicionar produto</button>`) + `<div class="grid product-grid">${db.products.length?db.products.map(p=>productCard(p)).join(""):`<div class="empty">Nenhum produto cadastrado. Comece adicionando seu primeiro produto.</div>`}</div>`;
}
function productCard(p){
  const vs=variants(p);
  const body=p.type==="key" ? `<div class="mini-list">${vs.length ? vs.map(v=>`<div><span>${esc(v.label)}</span><b>${money(v.price)}</b></div>`).join("") : `<small class="muted">Sem planos configurados</small>`}</div>` : `<div class="product-meta"><span>Estoque: <b>${stockAvailable(p.id).length}</b></span><span>${money(p.price)}</span></div>`;
  return `<div class="card product-card"><span class="badge ${p.active?"green":"red"}">${p.active?"Ativo":"Inativo"} · ${p.type==="account"?"Conta":"Key"}</span><h3>${esc(p.name)}</h3><p>${esc(p.description||"Sem descrição")}</p>${body}<div class="actions" style="margin-top:12px"><button class="btn" data-product="${p.id}" data-action="editProduct">Editar</button><button class="btn" data-product="${p.id}" data-action="newStock">＋ Estoque</button></div></div>`;
}
function finance(c){
  const delivered=db.sales.filter(s=>s.status==="delivered"), revenue=delivered.reduce((a,s)=>a+Number(s.price),0), pending=db.sales.filter(s=>s.status==="pending").reduce((a,s)=>a+Number(s.price),0);
  const byProduct=db.products.map(p=>{const ss=delivered.filter(s=>s.productId===p.id);return {p,n:ss.length,total:ss.reduce((a,s)=>a+Number(s.price),0)}}).filter(x=>x.n);
  c.innerHTML=layout("Financeiro","Acompanhe faturamento e desempenho por produto.",`<button class="btn" data-action="export">⇩ Exportar dados</button>`) + `<div class="grid cards"><div class="card"><div class="stat-top">Faturamento</div><div class="stat-value">${money(revenue)}</div><div class="stat-sub">vendas entregues</div></div><div class="card"><div class="stat-top">Ticket médio</div><div class="stat-value">${money(delivered.length?revenue/delivered.length:0)}</div><div class="stat-sub">por venda</div></div><div class="card"><div class="stat-top">A receber</div><div class="stat-value yellow">${money(pending)}</div><div class="stat-sub">vendas pendentes</div></div><div class="card"><div class="stat-top">Clientes</div><div class="stat-value">${db.clients.length}</div><div class="stat-sub">cadastrados</div></div></div><section class="section" style="margin-top:14px"><div class="section-head"><b>Desempenho por produto</b></div>${byProduct.length?`<table><thead><tr><th>Produto</th><th>Vendas</th><th>Faturamento</th><th>Preço médio</th></tr></thead><tbody>${byProduct.sort((a,b)=>b.total-a.total).map(x=>`<tr><td><b>${esc(x.p.name)}</b></td><td>${x.n}</td><td>${money(x.total)}</td><td>${money(x.total/x.n)}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">Ainda não há vendas entregues.</div>`}</section>`;
}
function automation(c){
  c.innerHTML=layout("Automação","Modelos gerais de entrega. O Discord de cada key pode substituir o padrão global.",`<button class="btn primary" data-action="saveSettings">Salvar modelos</button>`) + `<div class="grid two"><section class="section"><div class="section-head"><b>Modelo para Contas</b><span>variáveis</span></div><div style="padding:16px"><textarea class="textarea" id="autoAccount" style="min-height:300px">${esc(db.settings.accountTemplate)}</textarea><div class="notice" style="margin-top:12px">{produto} {nick} {senha} {emailLine} {discord} {cliente} {observacaoLine}</div></div></section><section class="section"><div class="section-head"><b>Modelo para Keys</b><span>variáveis</span></div><div style="padding:16px"><textarea class="textarea" id="autoKey" style="min-height:300px">${esc(db.settings.keyTemplate)}</textarea><div class="notice" style="margin-top:12px">{produto} {key} {duracao} {validade} {discord} {cliente} {observacaoLine}</div></div></section></div>`;
}
function audit(c){
  c.innerHTML=layout("Auditoria","Registro das principais ações realizadas no painel.",`<button class="btn" data-action="clearAudit">Limpar histórico</button>`) + `<section class="section">${db.audit.length?`<table><thead><tr><th>Data</th><th>Ação</th><th>Detalhe</th><th>Usuário</th></tr></thead><tbody>${db.audit.map(a=>`<tr><td>${new Date(a.date).toLocaleString("pt-BR")}</td><td><b>${esc(a.action)}</b></td><td>${esc(a.detail)}</td><td>${esc(a.user)}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">Nenhuma ação registrada.</div>`}</section>`;
}

function team(c){
  if(me.role!=="owner"){page="dashboard";return render();}
  c.innerHTML=layout("Equipe","Gerencie quem pode acessar o painel Tigelinha.",`<button class="btn primary" data-action="newTeamUser">＋ Novo usuário</button>`) + `<div class="role-grid"><div class="role-card"><b>Dono</b><small>Acesso total ao sistema e à equipe.</small></div><div class="role-card"><b>Administrador</b><small>Produtos, estoque, vendas, configurações e auditoria.</small></div><div class="role-card"><b>Vendedor / Ajudante</b><small>Clientes, estoque e criação de vendas.</small></div><div class="role-card"><b>Suporte</b><small>Consulta os dados liberados, sem alterar vendas ou estoque.</small></div></div><section class="section" style="margin-top:14px">${db.profiles.length?`<table><thead><tr><th>Nome</th><th>Usuário</th><th>Cargo</th><th>Status</th><th></th></tr></thead><tbody>${db.profiles.map(p=>`<tr><td><b>${esc(p.displayName||"—")}</b></td><td>${esc(p.username||"—")}</td><td>${esc(roleNames[p.role]||p.role)}</td><td>${p.active?statusBadge("available"):statusBadge("unavailable")}</td><td>${p.id!==me.id?`<button class="btn" data-user="${p.id}" data-action="toggleUser">${p.active?"Desativar":"Ativar"}</button>`:"Sua conta"}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">Nenhum usuário.</div>`}</section>`;
}
function newTeamUser(){openModal("Novo usuário da equipe",`<div class="notice">A conta será criada de forma segura no Supabase. A senha não fica salva no painel.</div><div class="form-grid"><div class="field"><label>Nome</label><input class="input" id="tuName" placeholder="Ex.: João"></div><div class="field"><label>Usuário</label><input class="input" id="tuUsername" placeholder="joao"></div><div class="field full"><label>E-mail</label><input class="input" id="tuEmail" type="email"></div><div class="field"><label>Senha inicial</label><input class="input" id="tuPassword" type="password" minlength="8"></div><div class="field"><label>Cargo</label><select class="select" id="tuRole"><option value="admin">Administrador</option><option value="seller">Vendedor / Ajudante</option><option value="support">Suporte</option></select></div></div>`,`<button class="btn" data-action="closeModal">Cancelar</button><button class="btn primary" data-action="createTeamUser">Criar usuário</button>`);}
async function createTeamUser(){const body={email:document.getElementById("tuEmail").value.trim(),password:document.getElementById("tuPassword").value,username:document.getElementById("tuUsername").value.trim(),display_name:document.getElementById("tuName").value.trim(),role:document.getElementById("tuRole").value};if(!body.email||body.password.length<8||!body.username||!body.display_name)return toast("Preencha os dados e use senha com 8+ caracteres.","error");const {data,error}=await sb.functions.invoke("create-team-user",{body});if(error||data?.error)return toast(data?.error||"A função segura de criar usuários ainda não foi instalada no Supabase.","error");await loadData();closeModal();render();toast("Usuário criado!");}
async function toggleUser(id){const p=db.profiles.find(x=>x.id===id);if(!p)return;const {error}=await sb.from("profiles").update({active:!p.active}).eq("id",id);if(error)return toast(error.message,"error");await log(p.active?"Usuário desativado":"Usuário ativado",p.username,"profile",id);await loadData();render();}

function settings(c){
  const keyProducts=db.products.filter(p=>p.type==="key");
  c.innerHTML=layout("Configurações","Configure a loja e os canais de cada produto. Cada plano de key pode ter seu próprio Discord, preço e mensagem.",`<button class="btn primary" data-action="saveSettings">Salvar alterações</button>`) + `
  <div class="grid two">
    <section class="section"><div class="section-head"><b>Loja</b><span>geral</span></div><div style="padding:18px" class="form-grid"><div class="field full"><label>Nome da loja</label><input class="input" id="setName" value="${esc(db.settings.storeName)}"></div><div class="field full"><label>Discord padrão</label><input class="input" id="setSupport" value="${esc(db.settings.globalSupport)}" placeholder="Usado somente quando o produto/plano não tiver Discord próprio"></div><div class="field"><label>Moeda</label><input class="input" value="BRL" disabled></div></div></section><section class="section"><div class="section-head"><b>Aparência</b><span>logo da loja</span></div><div style="padding:18px"><div class="logo-preview-wrap"><img id="logoPreview" src="${esc(db.settings.logoUrl||'tigelinha-logo.webp')}" alt="Logo"></div><div class="field" style="margin-top:14px"><label>Escolher nova imagem</label><input class="input" id="logoFile" type="file" accept="image/png,image/jpeg,image/webp"></div><div class="notice" style="margin-top:12px">A logo aparece no login e no menu. PNG, JPG ou WEBP, até 5 MB.</div><button class="btn primary" data-action="uploadLogo">Alterar logo</button> <button class="btn" data-action="resetLogo">Usar logo padrão</button></div></section>
    <section class="section"><div class="section-head"><b>Produtos e planos</b><span>${keyProducts.length} produtos de key</span></div><div style="padding:14px">${db.products.length?db.products.map(p=>`<div class="setting-product"><div><b>${esc(p.name)}</b><small>${p.type==="key"?`${variants(p).length} planos configurados`:`Produto de conta`}</small></div><button class="btn" data-product="${p.id}" data-action="editProduct">Configurar</button></div>`).join(""):`<div class="empty">Cadastre um produto para configurar os dados.</div>`}</div></section>
  </div>`;
}

function openModal(title,body,foot=`<button class="btn" data-action="closeModal">Fechar</button>`){document.getElementById("modalRoot").innerHTML=`<div class="modal-back"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" data-action="closeModal">×</button></div><div class="modal-body">${body}</div><div class="modal-foot">${foot}</div></div></div>`;}

function newProduct(id=null){
  const p=id?product(id):{type:"key",name:"",description:"",price:0,low:3,active:true,variants:defaultVariants()};
  openModal(id?"Configurar produto":"Adicionar produto",`
    <div class="form-grid">
      <div class="field"><label>Tipo</label><select class="select" id="pType" ${id?"disabled":""}><option value="account" ${p.type==="account"?"selected":""}>👤 Conta</option><option value="key" ${p.type==="key"?"selected":""}>🔑 Key</option></select></div>
      <div class="field"><label>Nome do produto</label><input class="input" id="pName" value="${esc(p.name)}" placeholder="Ex.: FiveM External"></div>
      <div class="field"><label>Preço sugerido</label><input class="input" type="number" step=".01" id="pPrice" value="${p.price||0}"></div><div class="field"><label>Alerta de estoque abaixo de</label><input class="input" type="number" id="pLow" value="${p.low??3}"></div>
      <div class="field"><label>Status</label><select class="select" id="pActive"><option value="true" ${p.active!==false?"selected":""}>Ativo</option><option value="false" ${p.active===false?"selected":""}>Inativo</option></select></div>
      <div class="field full"><label>Descrição</label><textarea class="textarea" id="pDesc">${esc(p.description||"")}</textarea></div>
    </div>
    <div id="keyPlansBox" style="margin-top:16px"></div>
  `,`<button class="btn" data-action="closeModal">Cancelar</button><button class="btn primary" data-product="${id||""}" data-action="saveProduct">Salvar produto</button>`);
  const typeEl=document.getElementById("pType");
  const refresh=()=>renderPlanEditor(document.getElementById("keyPlansBox"), typeEl.value, p);
  typeEl.addEventListener("change",refresh); refresh();
}
function defaultVariants(){return ["Diário","Semanal","Mensal","Lifetime"].map(label=>({id:crypto.randomUUID(),label,price:0,discord:"",template:""}));}
function renderPlanEditor(box,type,p){
  if(type!=="key"){box.innerHTML=`<div class="notice">Produtos de conta usam o preço cadastrado em cada item do estoque e o Discord padrão da loja, salvo configuração específica no item.</div>`;return;}
  const vs=variants(p).length?variants(p):defaultVariants();
  box.innerHTML=`<section class="section"><div class="section-head"><b>Planos da key</b><span>preço + Discord + template</span></div><div style="padding:12px"><div class="plan-editor">${vs.map((v,i)=>`<div class="plan-row" data-plan-index="${i}"><div class="plan-title">${esc(v.label)}</div><input class="input plan-price" type="number" step=".01" value="${Number(v.price)||0}" placeholder="Preço"><input class="input plan-discord" value="${esc(v.discord||"")}" placeholder="Discord deste plano"><input class="input plan-template" value="${esc(v.template||"")}" placeholder="Template opcional; vazio usa o modelo geral"></div>`).join("")}</div></div></section>`;
}
function readPlans(){
  return [...document.querySelectorAll(".plan-row")].map((row,i)=>{const labels=["Diário","Semanal","Mensal","Lifetime"];return {id:crypto.randomUUID(),label:labels[i]||`Plano ${i+1}`,price:Number(row.querySelector(".plan-price")?.value)||0,discord:row.querySelector(".plan-discord")?.value.trim()||"",template:row.querySelector(".plan-template")?.value||""};});
}
function newStock(prefProduct=""){
  const pid=prefProduct||db.products.find(p=>p.active)?.id||"";
  if(!pid){toast("Cadastre um produto primeiro.","error");return;}
  openModal("Adicionar item ao estoque",`<div class="form-grid"><div class="field full"><label>Produto</label><select class="select" id="stProduct">${db.products.filter(p=>p.active).map(p=>`<option value="${p.id}" ${p.id===pid?"selected":""}>${esc(p.name)} · ${p.type==="account"?"Conta":"Key"}</option>`).join("")}</select></div><div id="stockDynamic" class="full"></div></div>`,`<button class="btn" data-action="closeModal">Cancelar</button><button class="btn primary" data-action="saveStock">Adicionar ao estoque</button>`);
  updateStockFields(); document.getElementById("stProduct").addEventListener("change",updateStockFields);
}
function updateStockFields(){
  const p=product(document.getElementById("stProduct").value),box=document.getElementById("stockDynamic"); if(!p)return;
  const vs=variants(p);
  const planOptions=vs.length ? vs.map(v=>`<option value="${v.id}">${esc(v.label)} · ${money(v.price)}</option>`).join("") : `<option value="">Configure os planos primeiro</option>`;
  const specific=p.type==="account"
    ? `<div class="field"><label>Senha</label><input class="input" id="stPass"></div><div class="field"><label>Email (opcional)</label><input class="input" id="stEmail"></div>`
    : `<div class="field"><label>Duração</label><select class="select" id="stVariant">${planOptions}</select></div>`;
  const initialPrice=p.type==="key" ? (vs[0]?.price||0) : (p.price||0);
  const mainLabel=p.type==="account" ? "Nick" : "Key";
  const mainPlaceholder=p.type==="account" ? "Ex.: jogador123" : "XXXX-XXXX-XXXX";
  box.innerHTML=`<div class="form-grid"><div class="field"><label>${mainLabel}</label><input class="input" id="stMain" placeholder="${mainPlaceholder}"></div>${specific}<div class="field"><label>Preço de venda</label><input class="input" type="number" step=".01" id="stPrice" value="${initialPrice}"></div><div class="field"><label>Status</label><select class="select" id="stStatus"><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="unavailable">Indisponível</option></select></div><div class="field full"><label>Observação interna</label><textarea class="textarea" id="stObs" placeholder="Informações internas..."></textarea></div></div>`;
  const vEl=document.getElementById("stVariant"); if(vEl)vEl.addEventListener("change",()=>{const v=variant(p,vEl.value);document.getElementById("stPrice").value=v.price||0;});
}
function viewStock(pid){
  const p=product(pid),rows=db.stock.filter(s=>s.productId===pid);
  openModal(`Estoque • ${esc(p.name)}`,`<div class="detail"><div class="mini"><span>Disponíveis</span><b>${rows.filter(s=>s.status==="available").length}</b></div><div class="mini"><span>Reservados</span><b>${rows.filter(s=>s.status==="reserved").length}</b></div><div class="mini"><span>Total</span><b>${rows.length}</b></div></div><div class="section" style="margin-top:15px">${rows.length?`<table><thead><tr><th>Item</th><th>Plano</th><th>Preço</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.type==="account"?s.username:s.key)}</td><td>${esc(variant(p,s.variantId).label||"—")}</td><td>${money(s.price)}</td><td>${statusBadge(s.status)}</td><td><button class="btn" data-stock="${s.id}" data-action="stockDetail">Abrir</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">Sem itens cadastrados.</div>`}</div>`,`<button class="btn" data-action="closeModal">Fechar</button><button class="btn primary" data-product="${pid}" data-action="newStock">＋ Adicionar item</button>`);
}
function stockDetail(id){
  const s=db.stock.find(x=>x.id===id),p=product(s.productId),vs=variants(p);
  openModal(`Item de estoque • ${esc(p.name)}`,`<div class="notice">Dados internos usados na entrega.</div><div class="form-grid">${s.type==="account"?`<div class="field"><label>Nick</label><input class="input" id="edMain" value="${esc(s.username||"")}"></div><div class="field"><label>Senha</label><input class="input" id="edPass" value="${esc(s.password||"")}"></div><div class="field full"><label>Email</label><input class="input" id="edEmail" value="${esc(s.email||"")}"></div>`:`<div class="field full"><label>Key</label><input class="input" id="edMain" value="${esc(s.key||"")}"></div><div class="field"><label>Duração</label><select class="select" id="edVariant">${vs.map(v=>`<option value="${v.id}" ${v.id===s.variantId?"selected":""}>${esc(v.label)}</option>`).join("")}</select></div>`}<div class="field"><label>Preço</label><input class="input" type="number" step=".01" id="edPrice" value="${s.price||0}"></div><div class="field"><label>Status</label><select class="select" id="edStatus"><option value="available" ${s.status==="available"?"selected":""}>Disponível</option><option value="reserved" ${s.status==="reserved"?"selected":""}>Reservado</option><option value="sold" ${s.status==="sold"?"selected":""}>Vendido</option><option value="unavailable" ${s.status==="unavailable"?"selected":""}>Indisponível</option></select></div><div class="field full"><label>Observação</label><textarea class="textarea" id="edObs">${esc(s.observation||"")}</textarea></div></div>`,`<button class="btn danger" data-stock="${id}" data-action="deleteStock">Excluir</button><button class="btn" data-action="closeModal">Cancelar</button><button class="btn primary" data-stock="${id}" data-action="updateStock">Salvar</button>`);
}
function newClient(){openModal("Novo cliente",`<div class="form-grid"><div class="field full"><label>Nome interno</label><input class="input" id="clName" placeholder="Nome do cliente"></div><div class="field full"><label>Discord</label><input class="input" id="clDiscord" placeholder="@usuario ou perfil"></div><div class="field full"><label>Observações internas</label><textarea class="textarea" id="clNotes"></textarea></div></div>`,`<button class="btn" data-action="closeModal">Cancelar</button><button class="btn primary" data-action="saveClient">Cadastrar cliente</button>`);}
function clientDetail(id){const cl=client(id),ss=db.sales.filter(s=>s.clientId===id);openModal(`Cliente • ${esc(cl.name)}`,`<div class="detail"><div class="mini"><span>Compras</span><b>${ss.length}</b></div><div class="mini"><span>Total</span><b>${money(ss.reduce((a,s)=>a+Number(s.price),0))}</b></div><div class="mini"><span>Discord</span><b style="font-size:10px">${esc(cl.discord||"—")}</b></div></div><div class="notice" style="margin-top:14px">${esc(cl.notes||"Sem observações internas.")}</div><h3 style="font-size:12px">Histórico</h3>${salesTable(ss)}`,`<button class="btn" data-action="closeModal">Fechar</button>`);}

function newSale(){
  const available=db.stock.filter(s=>s.status==="available");
  if(!available.length){toast("Não há itens disponíveis no estoque.","error");return;}
  openModal("Nova venda",`<div class="notice">O produto, plano, Discord e mensagem são definidos automaticamente pela configuração do item.</div><div class="form-grid"><div class="field full"><label>Item do estoque</label><select class="select" id="saleStock">${available.map(s=>{const p=product(s.productId),v=variant(p,s.variantId);return `<option value="${s.id}">${esc(p.name)} · ${esc(v.label||"Conta")} · ${esc(s.type==="account"?s.username:s.key)} · ${money(s.price)}</option>`}).join("")}</select></div><div class="field"><label>Cliente</label><select class="select" id="saleClient"><option value="">＋ Cadastrar depois</option>${db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select></div><div class="field"><label>Valor da venda</label><input class="input" id="salePrice" type="number" step=".01"></div><div class="field"><label>Pagamento</label><select class="select" id="salePayment"><option>Pix</option><option>Cartão</option><option>Saldo</option><option>Outro</option></select></div><div class="field"><label>Status</label><select class="select" id="saleStatus"><option value="delivered">Entregue</option><option value="pending">Pendente</option></select></div><div class="field full"><label>Observação</label><textarea class="textarea" id="saleNote"></textarea></div></div>`,`<button class="btn" data-action="closeModal">Cancelar</button><button class="btn primary" data-action="confirmSale">Confirmar venda e gerar entrega</button>`);
  const ss=document.getElementById("saleStock");ss.addEventListener("change",()=>{const s=db.stock.find(x=>x.id===ss.value);document.getElementById("salePrice").value=s?.price||0;});ss.dispatchEvent(new Event("change"));
}
function generateDelivery(s){
  const st=db.stock.find(x=>x.id===s.stockId),p=product(s.productId),cl=client(s.clientId),v=variant(p,s.variantId);
  const cfg=p.type==="key"?v:{};
  const tpl=(cfg.template||"") || (p.type==="account"?db.settings.accountTemplate:db.settings.keyTemplate);
  const discord=cfg.discord || p.discord || db.settings.globalSupport || "";
  const vars={produto:p.name,nick:st?.username||"",senha:st?.password||"",key:st?.key||"",validade:st?.validity||v.label||"",duracao:v.label||st?.validity||"",discord,cliente:cl.name||"",emailLine:st?.email?`\n📧 Email: ${st.email}`:"",observacaoLine:st?.observation?`\n📝 ${st.observation}`:""};
  return tpl.replace(/\{(\w+)\}/g,(_,k)=>vars[k]??"").replace(/\\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();
}
function saleDetail(id){const s=db.sales.find(x=>x.id===id),p=product(s.productId),cl=client(s.clientId),st=db.stock.find(x=>x.id===s.stockId),v=variant(p,s.variantId);openModal(`Venda • ${esc(s.id)}`,`<div class="detail"><div class="mini"><span>Cliente</span><b>${esc(cl.name||"—")}</b></div><div class="mini"><span>Produto</span><b>${esc(p.name||"—")}</b></div><div class="mini"><span>Plano</span><b>${esc(v.label||"—")}</b></div><div class="mini"><span>Valor</span><b>${money(s.price)}</b></div><div class="mini"><span>Pagamento</span><b>${esc(s.payment||"—")}</b></div><div class="mini"><span>Status</span><b>${statusBadge(s.status)}</b></div></div><div class="notice" style="margin-top:15px">Observação interna: ${esc(s.note||"Nenhuma")}</div><h3 style="font-size:12px">Mensagem de entrega</h3><div class="delivery">${esc(s.delivery||generateDelivery(s))}</div>`,`<button class="btn danger" data-sale="${id}" data-action="deleteSale">Excluir venda</button><button class="btn" data-action="closeModal">Fechar</button><button class="btn primary" data-sale="${id}" data-action="copyDelivery">Copiar entrega</button>`);}

async function saveProduct(id){
  const name=document.getElementById("pName").value.trim();if(!name)return toast("Informe o nome do produto.","error");
  const type=document.getElementById("pType").value,low=Number(document.getElementById("pLow").value)||0,active=document.getElementById("pActive").value==="true",description=document.getElementById("pDesc").value.trim();
  let pid=id;
  if(id){const {error}=await sb.from("products").update({name,description,low_stock:low,active}).eq("id",id);if(error)return toast(error.message,"error");}
  else {const {data,error}=await sb.from("products").insert({name,description,type,low_stock:low,active}).select().single();if(error)return toast(error.message,"error");pid=data.id;}
  if(type==="key"){
    const plans=readPlans(); const old=variants(product(id));
    for(let i=0;i<plans.length;i++){const v=plans[i],oldv=old[i];const payload={product_id:pid,name:v.label,duration_type:["daily","weekly","monthly","lifetime"][i]||"custom",price:v.price,discord_url:v.discord||null,delivery_template:v.template||null,active:true};let res=oldv?await sb.from("product_plans").update(payload).eq("id",oldv.id):await sb.from("product_plans").insert(payload);if(res.error)return toast(res.error.message,"error");}
  }
  await log(id?"Produto atualizado":"Produto criado",name,"product",pid);await loadData();closeModal();render();toast("Produto salvo!");
}
async function saveStock(){
 const p=product(document.getElementById("stProduct").value),main=document.getElementById("stMain").value.trim();if(!main)return toast("Preencha o item.","error");const planId=p.type==="key"?(document.getElementById("stVariant")?.value||null):null;if(p.type==="key"&&!planId)return toast("Configure uma duração para este produto.","error");
 const payload={product_id:p.id,plan_id:planId,type:p.type,key_value:p.type==="key"?main:null,username:p.type==="account"?main:null,password:p.type==="account"?document.getElementById("stPass").value:null,email:p.type==="account"?document.getElementById("stEmail").value.trim()||null:null,price:Number(document.getElementById("stPrice").value)||0,status:document.getElementById("stStatus").value,observation:document.getElementById("stObs").value.trim()||null};
 const {data,error}=await sb.from("stock").insert(payload).select().single();if(error)return toast(error.code==="23505"?"Essa key já está cadastrada.":error.message,"error");await log("Estoque adicionado",p.name,"stock",data.id);await loadData();closeModal();render();toast("Item adicionado ao estoque!");
}
async function updateStock(id){const s=db.stock.find(x=>x.id===id);if(!s)return;const payload={price:Number(document.getElementById("edPrice").value)||0,status:document.getElementById("edStatus").value,observation:document.getElementById("edObs").value||null};if(s.type==="account")Object.assign(payload,{username:document.getElementById("edMain").value,password:document.getElementById("edPass").value,email:document.getElementById("edEmail").value||null});else Object.assign(payload,{key_value:document.getElementById("edMain").value,plan_id:document.getElementById("edVariant")?.value||s.variantId});const {error}=await sb.from("stock").update(payload).eq("id",id);if(error)return toast(error.message,"error");await log("Estoque atualizado",product(s.productId).name,"stock",id);await loadData();closeModal();render();toast("Item atualizado!");}
async function saveClient(){const name=document.getElementById("clName").value.trim();if(!name)return toast("Informe o nome.","error");const {data,error}=await sb.from("clients").insert({name,discord:document.getElementById("clDiscord").value.trim()||null,notes:document.getElementById("clNotes").value.trim()||null}).select().single();if(error)return toast(error.message,"error");await log("Cliente criado",name,"client",data.id);await loadData();closeModal();render();toast("Cliente cadastrado!");}
async function confirmSale(){
 const st=db.stock.find(x=>x.id===document.getElementById("saleStock").value),price=Number(document.getElementById("salePrice").value)||0;if(!st||!price)return toast("Selecione um item e informe o valor.","error");let cid=document.getElementById("saleClient").value;
 if(!cid){const name=prompt("Nome interno do cliente:");if(!name)return;const discord=prompt("Discord do cliente (opcional):")||"";const {data,error}=await sb.from("clients").insert({name,discord:discord||null}).select().single();if(error)return toast(error.message,"error");cid=data.id;}
 const code=nextSaleId(),status=document.getElementById("saleStatus").value;const temp={id:code,productId:st.productId,variantId:st.variantId,stockId:st.id,clientId:cid,price,payment:document.getElementById("salePayment").value,status,note:document.getElementById("saleNote").value.trim()};const delivery=generateDelivery(temp);
 const {data,error}=await sb.from("sales").insert({sale_code:code,product_id:st.productId,plan_id:st.variantId||null,stock_id:st.id,client_id:cid,price,payment_method:temp.payment,status,note:temp.note||null,delivery_message:delivery,created_by:session.user.id}).select().single();if(error)return toast(error.message,"error");if(status!=="cancelled"){const u=await sb.from("stock").update({status:"sold"}).eq("id",st.id).eq("status","available").select("id").maybeSingle();if(u.error||!u.data){await sb.from("sales").delete().eq("id",data.id);return toast("Este item acabou de ser vendido ou alterado por outro usuário.","error");}}
 await log("Venda criada",`${code} • ${product(st.productId).name} • ${money(price)}`,"sale",data.id);await loadData();closeModal();render();const sale=db.sales.find(x=>x.uuid===data.id);openModal(`Venda criada • ${code}`,`<div class="notice">Venda registrada no banco e item baixado do estoque.</div><div class="delivery">${esc(delivery)}</div>`,`<button class="btn" data-action="closeModal">Fechar</button><button class="btn primary" data-sale="${sale?.id||code}" data-action="copyDelivery">Copiar mensagem</button>`);toast("Venda registrada!");
}
async function uploadLogo(){const f=document.getElementById("logoFile")?.files?.[0];if(!f)return toast("Escolha uma imagem.","error");if(f.size>5*1024*1024)return toast("A imagem deve ter no máximo 5 MB.","error");const ext=(f.name.split(".").pop()||"png").toLowerCase();const path=`store-logo.${ext}`;const {error}=await sb.storage.from("branding").upload(path,f,{upsert:true,contentType:f.type});if(error)return toast(error.message,"error");const {data}=sb.storage.from("branding").getPublicUrl(path);const url=data.publicUrl+`?v=${Date.now()}`;const {error:e2}=await sb.from("settings").update({logo_url:url,updated_at:new Date().toISOString()}).eq("id",1);if(e2)return toast(e2.message,"error");await loadData();render();toast("Logo atualizada!");}
async function resetLogo(){const {error}=await sb.from("settings").update({logo_url:null,updated_at:new Date().toISOString()}).eq("id",1);if(error)return toast(error.message,"error");await loadData();render();toast("Logo padrão restaurada!");}
async function saveSettings(){const payload={updated_at:new Date().toISOString()};if(document.getElementById("setName")){payload.store_name=document.getElementById("setName").value.trim()||"Tigelinha";payload.global_support=document.getElementById("setSupport").value.trim()||null;}if(document.getElementById("autoAccount"))payload.default_account_template=document.getElementById("autoAccount").value;if(document.getElementById("autoKey"))payload.default_key_template=document.getElementById("autoKey").value;const {error}=await sb.from("settings").update(payload).eq("id",1);if(error)return toast(error.message,"error");await log("Configurações atualizadas","Preferências da loja","settings","1");await loadData();render();toast("Configurações salvas!");}
async function deleteSale(id){const sale=db.sales.find(x=>x.id===id);if(!sale)return;const p=product(sale.productId),st=db.stock.find(x=>x.id===sale.stockId);if(!confirm(`Excluir a venda ${sale.id} de ${p.name||"produto"}?\n\nSe o item ainda estiver vendido, ele volta para disponível.`))return;const {error}=await sb.from("sales").delete().eq("id",sale.uuid);if(error)return toast(error.message,"error");if(st&&st.status==="sold")await sb.from("stock").update({status:"available"}).eq("id",st.id);await log("Venda excluída",`${sale.id} • ${p.name||"Produto"} • ${money(sale.price)}`,"sale",sale.uuid);await loadData();closeModal();render();toast("Venda excluída e item devolvido ao estoque.");}
function copyDelivery(id){const s=db.sales.find(x=>x.id===id);if(!s)return;navigator.clipboard?.writeText(s.delivery||generateDelivery(s)).then(()=>toast("Mensagem copiada!")).catch(()=>toast("Não foi possível copiar automaticamente.","error"));}
function closeModal(){document.getElementById("modalRoot").innerHTML="";}
function toast(msg,type="ok"){const t=document.getElementById("toast");t.textContent=msg;t.className="show "+type;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className="",2500);}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`tigelinha-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}

document.addEventListener("click",async e=>{
 const n=e.target.closest("[data-page]");if(n){page=n.dataset.page;render();return;}const a=e.target.closest("[data-action]");if(!a)return;const act=a.dataset.action;
 if(act==="logout")return sb.auth.signOut(); if(act==="closeModal")closeModal(); if(act==="newProduct")newProduct(); if(act==="editProduct")newProduct(a.dataset.product); if(act==="saveProduct")await saveProduct(a.dataset.product||null); if(act==="newStock")newStock(a.dataset.product||""); if(act==="viewStock")viewStock(a.dataset.product); if(act==="stockDetail")stockDetail(a.dataset.stock); if(act==="saveStock")await saveStock(); if(act==="updateStock")await updateStock(a.dataset.stock);
 if(act==="deleteStock"&&confirm("Excluir este item do estoque?")){const {error}=await sb.from("stock").delete().eq("id",a.dataset.stock);if(error)return toast(error.message,"error");await log("Item excluído","Estoque","stock",a.dataset.stock);await loadData();closeModal();render();toast("Item excluído.");}
 if(act==="newClient")newClient();if(act==="saveClient")await saveClient();if(act==="clientDetail")clientDetail(a.dataset.client);if(act==="newSale")newSale();if(act==="confirmSale")await confirmSale();if(act==="saleDetail")saleDetail(a.dataset.sale);if(act==="deleteSale")await deleteSale(a.dataset.sale);if(act==="copyDelivery")copyDelivery(a.dataset.sale);if(act==="saveSettings")await saveSettings();if(act==="uploadLogo")await uploadLogo();if(act==="resetLogo")await resetLogo();if(act==="export")exportData();if(act==="newTeamUser")newTeamUser();if(act==="createTeamUser")await createTeamUser();if(act==="toggleUser")await toggleUser(a.dataset.user);
 if(act==="clearAudit"&&confirm("Limpar o histórico?")){toast("Por segurança, a auditoria não é apagada pelo painel.","error");}
});
document.addEventListener("click",e=>{const t=e.target.closest("[data-sale-mode]");if(t){document.querySelectorAll("[data-sale-mode]").forEach(x=>x.classList.remove("active"));t.classList.add("active");saleMode=t.dataset.saleMode;}});
document.addEventListener("input",e=>{if(e.target.id==="globalSearch"&&page==="sales")render();});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("globalSearch")?.focus();}});
document.querySelector(".app").style.display="none";boot();

